# Sử dụng image chính thức của Java 21
FROM openjdk:21-jdk-slim

# Tạo thư mục làm việc trong container
WORKDIR /app

# Copy file jar vào container
COPY target/chatbotai_backend-0.0.1-SNAPSHOT.jar /app/chatbot.jar

# Chạy ứng dụng Spring Boot khi container khởi động
ENTRYPOINT ["java", "-jar", "chatbot.jar"]

# Mở port 8080 (hoặc port mà ứng dụng sử dụng)
EXPOSE 8080
